### ISSUE TITLE
Programm Start with exception

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/SDRPager#1]
Hei Ralf,

Fortschritt ! Ich habe die Software auf meinem Raspi, bin mit VNC
drauf und starte sie aus einem Terminal raus. Darufhin gibt es einige
Fehlermeldungen _siehe angehängtes Bild_.
Die "librxtxSerial.so" ist im Verzeichnis /usr/lib/jni drin,
ich schätze daran dürfte es dann nicht liegen.

Wenn ich auf "Suchlauf starten" klicke passiert nichts, bis auf eine
Menge weitere Fehlermeldungen im Terminal. Brauchst du die auch ?

LG,
Jens
![sdrpager](https://cloud.githubusercontent.com/assets/16710361/18984199/6c609d76-86f1-11e6-96a6-8f429c885f37.png)

**Comment by menzerath** [comment]
Die `UnsupportedOperationException` scheint durch das TrayIcon ausgelöst zu werden, da dieses nicht hinzugefügt werden kann (würde auf die verwendete Desktopumgebung auf dem Pi tippen).
Da das TrayIcon allerdings keine wichtige Funktion hat, sollte das Programm auch ohne weiterlaufen.

Die weiteren Fehlermeldungen wären noch interessant. Und außerdem muss das Programm als root ausgeführt werden, damit es auf serielle Ports / GPIO-Pins zugreifen darf...

**Comment by menzerath** [comment]
Gibt es hierzu Neuigkeiten?
