### ISSUE TITLE
SocketThread exception

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/SDRPager#10]
Gerade gesehen 
![thread](https://cloud.githubusercontent.com/assets/16710361/20069870/97a71028-a51e-11e6-8dd9-97e10c2462b0.PNG)

**Comment by Taronyu** [comment]
Ich habe das eventuell schon in meinem Refactoring Branch abgefangen, müssten wir mal testen, wenn ich soweit bin.

**Comment by Taronyu** [comment]
Hat sich das eigentlich mit der neuen Version geklärt?

**Comment by dh3wr** [comment]
Ist bisher nicht mehr aufgetreten, bei Bedarf reopen
