### ISSUE TITLE
TX Delay (Zeit zwischen GPIO an und Audio Start unnötig lang)

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/SDRPager#11]
Wenn man das TX Delay in der GUI auf 0 ms stellt, ist trotzdem der Sender 0.52 s vor dem Beginn des Audio (also der Präambel) bereits an. Für eine gute Kanalausnutzung sollte das nicht der Fall sein. Kann man das verbessern?
![txdelay1](https://cloud.githubusercontent.com/assets/16710361/20116293/026b2d80-a5fc-11e6-8f0c-9dc674b73167.PNG)
![txdelay2](https://cloud.githubusercontent.com/assets/16710361/20116292/026a3d62-a5fc-11e6-9695-d8dca005946c.PNG)

**Comment by menzerath** [comment]
Der GPIO-Pin wird im Code direkt nach der seriellen Schnittstelle aktiviert / deaktiviert.
Daraufhin folgt direkt der `AudioEncoder.play(data);`-Aufruf...

Diese Verzögerung entsteht entweder durch den Pi selbst oder durch die `encode`-Methode, die in der `play`-Methode zur Erzeugung der Audio-Daten aufgerufen wird.

**Comment by Taronyu** [comment]
So vom Code her sieht das ja folgendermaßen aus: Wenn eine Message verfügbar ist und es Zeit zum Senden ist, dann erzeuge die Codewörter und schalte den Sender ein. Dann wird das Play aufgerufen, das wiederum erst mal die Daten in Audio umwandeln muss, bevor der Audioclip abgespielt wird. Ich vermute, die Zeit geht an der Stelle verloren. Ich sehe da aktuell nur die Möglichkeit, den Sender wirklich erst beim Senden einzuschalten, also das innerhalb der play() Funktion zu regeln.

**Comment by dh3wr** [comment]
Marvin arbeitet dran. Er hat jetzt ein komplettes Test-Setup. Ich hoffe, dass wir bis heute Abend eine lauffähige Version habe, die wir dann mit deiner Thread-Änderung mergen können.
