### ISSUE TITLE
PTT Steuerung? V1.4

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/SDRPager#13]
Obwohl der aktive Zeitschlitz längst vorbei ist, kommt kein Set PTT to off.
Ist die Bezeichung ON / OFF eigentlich unabh. von der Invertierung?

![ptt](https://cloud.githubusercontent.com/assets/16710361/20173704/ab68032e-a73a-11e6-913e-df347391fa47.PNG)

**Comment by dh3wr** [comment]
Ja, On OFF ist unabh., also nur logisch zu verstehen. Es hat nichts mit dem tatsächlichen Pegel am GPIO Port zu tun.

**Comment by Taronyu** [comment]
Hängt das jetzt vielleicht mit der Änderung in #11 zusammen?

**Comment by menzerath** [comment]
Ja, das scheint der Grund für das Verhalten zu sein.
Komischerweise konnte ich das Problem jedoch nicht auf meinem Test-Pi nachvollziehen.

Die aktuelle Lösung (die auch zu funktionieren scheint) sieht so aus: der Scheduler lässt den AudioEncoder die Daten encodieren, schaltet PTT ein und lässt dann erst abspielen.
Der AudioEncoder schaltet dann PTT wieder aus, sobald das Abspielen beendet ist.
Damit kommt man bei einem eingestellten 0ms Delay auf ein tatsächliches Delay von ca. 0.055s.

**Comment by dh3wr** [comment]
Hat sich durch rewrite von scheduler.java erledigt.
