### ISSUE TITLE
Kommentar zum commit #39

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/SDRPager#14]
Fehler gefunden, get Data kommt nicht darauf klar, dass das Encoding schon einen Zeitschlitz vorher geschieht, da hier der aktuelle Zeitschlitz benutz wird, und der ist ja noch nicht erlaubt.

Nur als Gedankenstütze

**Comment by dh3wr** [comment]
Commit #40 enthält immer noch den Bug, aber schon mal Verbesserungen

**Comment by menzerath** [comment]
Sollte mittlerweile im `master`-Branch mit dem neuen Scheduler gefixt sein...
