### ISSUE TITLE
Search-Scheduler soll unabhängig von Zeitschlitzen sein

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/SDRPager#15]
Ich habe mir die Implementierung des SearchSchedulers angeschaut. Er basiert noch auf Zeitschlitzen, was aber für diesen Anwendungsfall keinen Sinn macht. Die Search-Sendnungen können beliebig ausgesendet werden. Also nach dem Schema:
Genertiere Funkruf mit aktuellem Correction Factor im Inhalt
Sende diesen aus und erhöhe den Corr Factor
Warte 1 Sek
Fange wieder oben an, wenn Corr Factor nicht >= 1.
Ich versuche das mal einzubauen.

**Comment by dh3wr** [comment]
Ich bin zu dumm dazu. Der Search Scheduler ist ja vom Scheduler abgeleitet, hat aber eigentlich damit nun nichts mehr zu tun. Im Grunde kann der ganze Timer weg, sondern einfach nur ein
while(CoorFactor >= 1)
{
Erstelle 2 Messages (einmal Uhrzeit, einmal CorrFactor als Inhalt)
Encodiere Message
Sende Message
Erhöhe CorrFactor um CorrFactorStep
Warte 1 Sek
}

Mir ist nicht klar, wie die ganze GUI-Operation hier anzusprechen ist, bzw. was sie anspricht. Insb. wie dann der Stop-Button die While-Schleife beenden kann. Und man sollte natürlich eine Verriegelung haben, dass der normaler Scheduler nicht während dessen was tut.

**Comment by dh3wr** [comment]
Marvin macht jetzt folgendes:
Der Search-Sched. wird weiterhin vom Sched. abgeleitet, aber mit 5 Sek. Intervall. Dadurch spart man sich die while Schleife. Jeder Durchlauf sendet 1 Mal und erhöht den Corr Factor. Ende durch Button oder wenn Corr-Factor >= 1

**Comment by menzerath** [comment]
Die Änderungen sind in Commit 93afe53668e91753b473b0166407dec084c0e7e1 enthalten.
Im einzelnen:
* [hier](https://github.com/rwth-afu/SDRPager/blob/93afe53668e91753b473b0166407dec084c0e7e1/raspager-sdr/src/main/java/de/rwth_aachen/afu/raspager/RasPagerService.java#L59)
* [und hier](https://github.com/rwth-afu/SDRPager/blob/93afe53668e91753b473b0166407dec084c0e7e1/raspager-sdr/src/main/java/de/rwth_aachen/afu/raspager/SearchScheduler.java#L22)

Das Ganze ist allerdings noch ungetestet!

**Comment by Taronyu** [comment]
Können wir das eigentlich schließen oder ist das noch aktuell?

**Comment by menzerath** [comment]
Die Änderungen sind drin und laut #26 scheint auch alles zu funktionieren...
