### ISSUE TITLE
IDE Dateien aus dem Repository ausschließen

### ISSUE THREAD

**Issue by Taronyu** [rwth-afu/SDRPager#16]
Bei Maven Projekten braucht man keine IDE-spezifischen Dateien im Repo. Den ganzen Kram kann man also rauswerfen, zumal man dann auch kein Durcheinander bekommt, wenn man verschiedene IDEs einsetzt.

**Comment by Taronyu** [comment]
Meine Eclipse Dateien sind jetzt schon mal raus und in der gitignore.

**Comment by menzerath** [comment]
Einerseits wäre ich auch dafür den Kram rauszuschmeißen, damit das Repo einigermaßen aufgeräumt bleibt.
Andererseits ist es auch praktisch, wenn man nach einem Clone direkt die IDE im Projektverzeichnis öffnen kann und z.B. die Code-Style Einstellungen übernommen hat.

EDIT: Werde auch gleich mal aufräumen...

**Comment by menzerath** [comment]
Jetzt scheint alles weg zu sein...

**Comment by Taronyu** [comment]
Sehr schön, danke :)
