### ISSUE TITLE
Start ohne Config-File nicht möglich

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/SDRPager#17]
Es erscheint SERVRE: Failed to load configuration file. raspaher.properties (No such file or directory)
Wenn man kein Konfig-File angibt.
Gibt man ein leeres File an, so gibt es java.util.NoSuchElementException: net.masters

Gibt man dann den Master, die Soundkarte und GPIO in der GUI an und klickt auf apply, dann auf Start Server kommt
Nullpointer Exception in  RasPagerService.startServer In RasPagerServer.java 105
Dort steht
srv.setGetTimeHandler(scheduler::getTime);

**Comment by Taronyu** [comment]
Ich habe es nicht getestet, sollte aber jetzt raus sein.

**Comment by dh3wr** [comment]
Siehe Kommentar zum Commit.

**Comment by Taronyu** [comment]
Ich habe mal eine neue Version hochgeladen.

**Comment by dh3wr** [comment]
Geht
