### ISSUE TITLE
Connect auch von nicht in der Masterliste eingetragenen IPs möglich

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/SDRPager#18]
![otherip](https://cloud.githubusercontent.com/assets/16710361/20794991/3f9105e2-b7cf-11e6-83f9-a3e721ecaa74.PNG)

Sollte zurückgewiesen werden, sonst macht die Liste keinen Sinn.

**Comment by dh3wr** [comment]
Ah, es ist hier die telnet-Aufrufende Maschine auch der PI selbst, auf dem das Java Programm läuft. Vielleicht daher? Aber auch der müsste sich ja mit seiner 44.225.164.52 IP melden und nicht mit localhost

**Comment by Taronyu** [comment]
Müsste im Commit da62e58 gefixt sein.
