### ISSUE TITLE
Search Scheduler geht nicht an

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/SDRPager#20]
Wenn ich auf Start in der aktuellen Version klicke, passiert genau nichts. Ist hier die Callback-Funktion nicht verlinkt?

**Comment by Taronyu** [comment]
Das war tatsächlich ein Bug, die Stelle hatte ich mir sogar schon markiert. Auf meinem Laptop ließ der Scheduler sich jetzt auch starten.
