### ISSUE TITLE
Commit #91: IP Filter geht nicht

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/SDRPager#22]
In commit #91 kommt nach starten des Server:
![ipfilter](https://cloud.githubusercontent.com/assets/16710361/20878904/8fc0d2b8-bad1-11e6-95fd-5a947f8f4de0.PNG)

Diese Meldung wiederholt sich ständig

**Comment by Taronyu** [comment]
Ein Sharable vergessen :-)
