### ISSUE TITLE
Searchscheduler startet ab Corr. Faktor aus Config

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/SDRPager#23]
Früher startete der SearchSched. mit dem am Slider eingestellten Wert. Nun wird anscheined der Wert aus der Config übernommen. Das bedeutet, dass man Werte kleiner als dem aus der Config nicht erreicht.
Möglichkeit 1: Slider-Wert als Start übernehmen
Mög. 2.: immer bei -1 anfangen.

**Comment by dh3wr** [comment]
Klick auf Apply übernimmt den aktuellen Slider Wert dennoch

**Comment by Taronyu** [comment]
Ohne Apply wird halt erst mal der Wert aus der config genommen. Ich kann das aber mal anpassen.

**Comment by dh3wr** [comment]
Nach Klick auf Apply ändert sich der Korr faktor überhaupt nicht mehr. Periodische Sendungen geschehen trotzdem.

**Comment by Taronyu** [comment]
Loggt der den Output? Eigentlich müsste da mit Level INFO was passieren. Sieht momentan danach aus, dass die Schrittweite nicht übernommen wird. Ist zumindest meine Vermutung.

**Comment by dh3wr** [comment]
Info: correction {0}

**Comment by Taronyu** [comment]
Die Stepsize wurde wirklich nicht übernommen.
