### ISSUE TITLE
StepSize wird nicht verwedet

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/SDRPager#24]
Wenn ich 0.1 eintrage, geschieht das GUI Update mit 0.1 Schritten, aber er sendet 2 Mal pro GUI Update. Als ob er noch 0.05 (mein vorheriger Wert) gespeichert hätten. Habe apply gedrückt vor dem Starten des Search Sched.

**Comment by dh3wr** [comment]
Vielleicht kann man in der Info-Ausgabe mal den aktuellen CorrektionFaktor ausgeben? Hier steht immer INFO: Correction{0}

**Comment by dh3wr** [comment]
Oh, Idee: Sendet er vielleicht 2 Mal, weil er auch 2 Nachrichten erzeugt? Eine mit der Uhrzeit und eine mit der nachricht? Dann wäre das kein Bug

**Comment by Taronyu** [comment]
Das könnte sein, es werden ja tatsächlich pro Update zwei Nachrichten gebaut. Ich habe mal ein Update mit Logging gemacht.

Edit: Hatte da einmal den alten Wert geloggt...

**Comment by dh3wr** [comment]
![2mail](https://cloud.githubusercontent.com/assets/16710361/20881256/d13e5a58-badb-11e6-9ecb-15b222ab607d.PNG)

2 Mal der gleiche Faktor, kein Empfang auf dem Skyper, obwohl bei Master-Verbindung empfang da ist.

**Comment by Taronyu** [comment]
Hast du schon die neuste Version probiert? Ich hatte da versehentlich 2x den alten correction Wert geloggt.

**Comment by dh3wr** [comment]
Teste gerade a745d26. Moment

**Comment by Taronyu** [comment]
Ich habe da noch einen Bug gefunden, der Slider wurde auch auf den alten Wert gesetzt.

**Comment by Taronyu** [comment]
Ich habe die Logik noch einmal überarbeitet.

**Comment by dh3wr** [comment]
Geht jetzt scheinbar.
![search](https://cloud.githubusercontent.com/assets/16710361/20881925/e9e44330-bade-11e6-89ec-80293b6bdca1.PNG)

**Comment by Taronyu** [comment]
Schön 👍
