### ISSUE TITLE
Kein Empfang der Nachricht beim SearchSched

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/SDRPager#26]
Die  Stepsize aus #24 wird wohl nun richtig gesetzt, aber kein Empfang. Könnte man mal die aus der GUI engelesene Skyper-Nummer ausgeben? Evtl. auch nochmal vergleich mit der früheren Implementation?
Der Correction-INFO-output kann wieder weg.

**Comment by dh3wr** [comment]
Was passiert denn im Else Fall
`if (!addr.isEmpty()) {`
`			String[] parts = new String[] { "#00 6", "1", addr, "3",`
`					String.format("correction=%+4.2f", sdr.getCorrection()) };`
`			addMessage(new Message(parts));`
`}`

**Comment by dh3wr** [comment]
Eine Meldung und erst gar nicht starten wäre schön...

**Comment by Taronyu** [comment]
Das Starten müsste im Commit ca62b60 gefixt sein. Warum nichts empfangen wird, habe ich aber noch nicht herausgefunden.

**Comment by Taronyu** [comment]
Ich habe den letzten Commit zum Teil wierder zurückgenommen, da die Behandlung der leeren Skyper-Adresse bereits in der runScheduler in RasPagerWindow erfolgte.

**Comment by dh3wr** [comment]
Auch mit einem anderen Skyper kein Empfang der Search-Sched Nachricht.

**Comment by dh3wr** [comment]
Bei Aussendung über DAPNET-Core makeloser Empfang.

**Comment by dh3wr** [comment]
Im alten Code steht
`addMessage(new Message(("#00 6:1:" + skyperAddress + ":3:correction=" + String.format("%+4.2f", AudioEncoder.correction)).split(":")));`

Ich vermute, dass die ":" fehlen?

Neuer Code
`		String addr = service.getWindow().getSkyperAddress();`
`		if (!addr.isEmpty()) {`
`			String[] parts = new String[] { "#00 6", "1", addr, "3",`
`					String.format("correction=%+4.2f", sdr.getCorrection()) };`
`addMessage(new Message(parts));`

**Comment by Taronyu** [comment]
Ich spar mir halt das split und baue das Array direkt auf. Kann sein, dass da noch was klemmt.

**Comment by dh3wr** [comment]
So sieht die Message vom Core aus
#00 6:1:BC1F:3:NACHTICHTENTEXT
Habe eine Log-Ausgabe eingebaut

**Comment by dh3wr** [comment]
Ist vielleicht die skyperadresse nicht hexadezimal wie sie vom Server kommt?

**Comment by Taronyu** [comment]
Das kann sein, wenn man die nicht in Hex eintippt, versuch die Adress bitte mal als Hex. Das sieht mir momentan stark danach aus, gute Idee.

**Comment by dh3wr** [comment]
Das Feld akzeptiert nur Zahlen. Aber ich habe kein Int2Hex im Code gefunden.

**Comment by dh3wr** [comment]
// search address
		searchAddress = new JTextField();
		searchAddress.setBounds(455, 434, 100, 18);
		searchAddress.addKeyListener(new KeyListener() {
			@Override
			public void keyTyped(KeyEvent event) {
				char key = event.getKeyChar();
				if ((key > '9' || key < '0')) {
					event.consume();
				}
			}

**Comment by dh3wr** [comment]
Ich habe einen Skyper mit 0x9002 als Adresse. Damit geht's. Also fehlt das String to Int to Hex

**Comment by Taronyu** [comment]
hihi, ich mach mal den hex convert rein und dann gucken wir mal.

**Comment by Taronyu** [comment]
Magst du es noch einmal versuchen?

**Comment by dh3wr** [comment]
Jetzt geht zwar die Korr Faktor Leiste nach oben, aber er sendet nicht mehr und auch auf der Commando-Zeile kommen keine Logs mehr.

**Comment by dh3wr** [comment]
Start und stop gehen noch, aber keine SearchScheduler senddata Logs mehr. Eigentlich gar keine Logs beim Search Sched. Der normale Server geht wohl noch

**Comment by Taronyu** [comment]
Da hab ich mal wieder ein if verbastelt, müsste jetzt wieder etwas machen.

**Comment by dh3wr** [comment]
Geht jetzt. #27 weiterhin offen und present.
