### ISSUE TITLE
Ende Search Sched liefert Exception

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/SDRPager#27]
Läuft durch, dann am Ende:

![endesearch](https://cloud.githubusercontent.com/assets/16710361/20886311/c18a3dec-baf5-11e6-8aef-263ac7b13cc4.PNG)

**Comment by Taronyu** [comment]
Sieht mir momentan nach einem Nebenläufigkeitsproblem beim Beenden aus, bin dran.

**Comment by Taronyu** [comment]
Müsste behoben sein. Das Problem hier war, dass der Transmitter geschlossen wird, während der Scheduler (timertask) noch läuft. Der Workaround ist ein bisschen hässlich, muss man mal sehen, ob das schöner geht.
