### ISSUE TITLE
Raspi Typ B+ kein Audio

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/SDRPager#29]
Submitter: Adolf Loosen
Habe die Version 1.4 mit meinem Raspi Typ B damit bekomme ich einen Connect zu SDA. Versuche ich das gleiche mit einem Raspi Typ B+ (Einstellung in der Software geändert auf betreffenden Raspi) bekomme ich keinen Connect.
Habt ihr schon mal den Connect damit erreicht?
Woran kann das liegen?

Habe im Moment das Problem ich bekomme keine NF aus dem Raspi raus, egal welche Soundkarte ich einstelle. Habe als Betriebssystem das Jessie drauf, als TRX den T7F und den Gm1200. 

Müsste mit dem Kopfhörer doch was hören. Ist mit beiden TRX einwandfrei mit dem Raspi Typ B gelaufen, erst ging die NF weg und dann auch die PTT. 

Für eine Antwort im voraus vielen Dank
Gruß
Adolf DL6KL

**Comment by dh3wr** [comment]
Zusammenfassung:
- RasP B: geht alles
- RasPi B+: kein PTT (über GPIO)
- RasPi B+: keine Audio-Ausgabe
- RasPi B+: kein Connect zum Master

**Comment by dh3wr** [comment]
Hast du auf beiden Geräten die gleiche Java-Version drauf?
Kannst du einfach nur die SD-Karten tauschen?
Das der TCP Connect zum DAPNET-Core nicht geht, ist sehr verwunderlich. Hier scheint ein noch tieferes Problem vorzuliegen, denn Netzwerkverbindungen sollten ja wohl sowohl auf den Pi-B als auch auf dem Pi-B+ ausreichend stabil laufen.

**Comment by dl6kl** [comment]
Bei beiden Geräten sind die gleichen Softwarversionen drauf

**Comment by dh3wr** [comment]
Du könntest mal zumindest die Audio-Ausgabe mit dem Linux-Programm aplay testen. Einfach aplay DATEINAME.wav auf der Konsole eingeben und höre, ob was kommt. Was die TCP Sache angeht, so habe ich keine Idee? Jemand sonst?

**Comment by dl6kl** [comment]
Die Ausgabe mit aplay habe ich heute morgen mal gemacht.
Ging nicht, als ich mit raspi-config-Audio von Auto auf Force 3,5 Klinke umgestellt hatte
ging der Raspbery Pi Typ B einwandfrei .
Ob das an dem Jessie lag keine Ahnung.
Gebe mich dann mal an den B+ dran.
Melde mich

**Comment by dl6kl** [comment]
Bekomme bei alles Soundkarten (default,0.0 und 0.1) die folgende Fehlermeldung
Der speaker-test läuft
Adresse (BC1F): 988b8
java.lang.IllegalArgumentException: Mixer not supported: ALSA [plughw:0,1], version 4.4.21+
	at javax.sound.sampled.AudioSystem.getMixer(AudioSystem.java:259)
	at javax.sound.sampled.AudioSystem.getClip(AudioSystem.java:557)
	at funkrufSlave.AudioEncoder.play(AudioEncoder.java:22)
	at funkrufSlave.AudioEncoder.play(AudioEncoder.java:63)
	at funkrufSlave.SearchScheduler.run(SearchScheduler.java:53)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
 I: 16.12.2016 17:32:07 correction: 0.0

**Comment by phl0** [comment]
Was sagt "aplay -l" bzw. "lsmod | grep snd"?

**Comment by dl6kl** [comment]
Also das Problem lag nicht an der Soundkarte die war in Ordnung.
Habe heute festgestellt das die 3,5mm Buchse auf der Platine defekt war.
habe provisorisch eine neue angelötet jetzt geht der Sound

**Comment by dl6kl** [comment]
mein letztes Problem ist jetzt der Connect.
Wenn ich den Server starte müsste folgende Meldung kommen:
Server is running
Set GPIO Port..
Die Meldung Set GPIO Port.... kommt nicht.
Habe den Suchlauf auf meinen Pager gemacht da folgt in 0,05er Schritten die Ausgabe auf meinen Pager, also müsste der GPIO Port ok sein (GM1200 geht auf Sendung)

**Comment by dh3wr** [comment]
Hast du wiringPi installiert? Wird das eigentlich noch gebraucht?

**Comment by dl6kl** [comment]
Habe wiringPi drauf werde es löschen und dann mal probieren

**Comment by dl6kl** [comment]
Habe wiringPi gelöscht der Raspi B läuft einwandfrei
Connect über GPIO 0

**Comment by dh3wr** [comment]
Damit erstmal gelößt.
