### ISSUE TITLE
Serieller Port Start Fehlermeldung

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/SDRPager#3]
https://twitter.com/DB9MAT/status/784795119857917952?cn=cmVwbHk%3D&refsrc=email
![cuqm_xkxgaazoxo jpg large](https://cloud.githubusercontent.com/assets/16710361/19215694/53cf6638-8da5-11e6-8b78-9f580e1bb820.jpg)

Angeblich gibt es den Port. Fehlen von sudo kann es nicht sein, da als root ausgeführt.

**Comment by menzerath** [comment]
Was mir spontan einfällt:
- Vor dem Start auf "Übernehmen" geklickt?
- RXTX-Dateien in das `/usr/lib/jni`-Verzeichnis kopiert und den Pfad als `-Djava.library.path=...` angegeben?

**Comment by dh3wr** [comment]
Es gibt noch eine weitere Fehlermeldung von Benutzern dazu:

root@raspberrypi:/opt/raspager/compiled_jars# java -Djava.library.path=/usr/lib/jni -jar FunkrufSlave.jar -configfile=/opt/raspager/compiled_jars/raspager.conf -nogui
FunkrufSlave - Version 1.3
by Ralf Wilke, Michael Delissen und Marvin Menzerath, powered by IHF RWTH Aachen
New Versions at www.afu.rwth-aachen.de

Exception in thread "main" java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.NullPointerException
at funkrufSlave.Main.initSerialPortComm(Main.java:165)
at funkrufSlave.Main.startServer(Main.java:288)
at funkrufSlave.Main.main(Main.java:503)
... 5 more
root@raspberrypi:/opt/raspager/compiled_jars#

Lösungsvorschlag:
ALT:
public static boolean initSerialPortComm() {
if (!mainWindow.useSerial()) return true;

NEU:
public static boolean initSerialPortComm() {
if (!Main.config.useSerial()) return true;

ALT:
public static boolean initGpioPortComm() {
if (!mainWindow.useGpio()) return true;

NEU:
public static boolean initGpioPortComm() {
if (!Main.config.useGpio()) return true;

Macht das Sinn?

**Comment by dh3wr** [comment]
Und was sind die notwendigen Aktionen, um das zu testen?

**Comment by menzerath** [comment]
Mit dem Fix habe ich auch [hier](https://github.com/dh3wr/SDRPager/tree/master/compiled_jars) eine neue JAR hochgeladen, die die Änderungen beinhalten sollte.

**Comment by menzerath** [comment]
Gibt es hierzu Neuigkeiten?
