### ISSUE TITLE
Wenn kein ordentliche GUI-Umgebung läuft, macht das Tray-Icon Probleme

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/SDRPager#30]
Bei db0kwe.ampr.org ist nur ein rudimentäres X11 installiert. Hier macht das Tray-Icon Probleme, da es wohl nicht weiß wo es sich hinzeichen soll. Es gibt ja keine Taskbar. Vielleicht kann man da ein "if" einbauen, das das abfängt?
![no_x](https://cloud.githubusercontent.com/assets/16710361/21141869/c3b00fb6-c13f-11e6-8245-4510caa42787.PNG)

**Comment by Taronyu** [comment]
Beim Start kann man nun mittels "--no-trayicon" das Laden des Tray Icons unterbinden.
