### ISSUE TITLE
RXTX nicht in compiled jar, insb. fehlen die .so Libs

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/SDRPager#4]
Auf einer frischen Java Installation muss man erst die Datei librxtxSerial.so nach %JAVA_HOME%/jre/lib/i386 kopieren und dazu von http://www.jcontrol.org/download/rxtx_de.html das ZIP herunterladen. Das sollte entweder automatisiert werden oder in der Readme stehen.

**Comment by dh3wr** [comment]
Ok, gerade gesehen. Steht da ;)  Für RPM basierte Systeme gibt es allerdings in SuSE 12.2 zumindest das Paket nicht. Daher den Download-Link bitte in Readme aufnehmen.

**Comment by menzerath** [comment]
In https://github.com/dh3wr/SDRPager/commit/6cf248d14c722a1eef56510f5f7413bc6ffe9098 hinzugefügt
