### ISSUE TITLE
Null Pointer exception bei Verbindungsaufbau mit DAPNET-Core

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/SDRPager#5]
![bug1](https://cloud.githubusercontent.com/assets/16710361/19739825/bc59c82c-9bbc-11e6-8e20-be4fb9171c63.PNG)
Sobald der DAPNET-Core die Verbindung zum SDRPager aufbaut kommt diese Fehlermeldung. Status ist laut Java-GUI "verbunden", aber der DAPNET-Core sagt weiterhin offline. 
![bug2](https://cloud.githubusercontent.com/assets/16710361/19739908/03251c7a-9bbd-11e6-96b6-518a87bda085.PNG)

**Comment by dh3wr** [comment]
Zur Info:
pi@pocsagtest:~ $ java -version
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) Client VM (build 25.65-b01, mixed mode)

**Comment by menzerath** [comment]
Die problematische Zeile in der `FunkrufProtocol`-Klasse lautet:

``` java
int time = Main.scheduler.getTime();
```

Allerdings haben wir die Klasse nie verändert...
Kannst du die Anwendung bitte einmal mit dem `-v` Parameter starten? Dann sollte der Log ausführlicher sein.
