### ISSUE TITLE
RasPi Auswahl "UNKNOWN"

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/SDRPager#7]
Ist das beabsichtigt?
![unknown](https://cloud.githubusercontent.com/assets/16710361/19740434/f551a5a8-9bbe-11e6-95c5-d3f925c858da.PNG)

**Comment by menzerath** [comment]
`UNKNOWN` wird von der GPIO-Library angeboten und ermöglicht die Auswahl von allen üblicherweise verfügbaren GPIO-Pins.
